# workflow name
name: workflow-03

# event >> trigger
#on: ["push"] # ["push", "pull_request"]
on:
  push:
    branches: [master] # when someone push to master branch the workflow will run


jobs:
  mac-os-config-name:
    # OS or platform
    runs-on: macos-11
    # steps
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      #- run: git clone https://github.com/fluendo/cerbero.git
      #- run: git clone https://gitlab.freedesktop.org/gstreamer/cerbero.git
      #- working-directory: ./cerbero
      - run: type -a openssl
      - run: echo "$PATH"
      - run: openssl version -a
      - run: openssl version -d
      - run: rustc --version
      - name: "rustup init automatic prompt"
        run:  printf "%sn" 1 | rustup-init 
      - run: rustc --version
      
      #- run: brew reinstall openssl@3
      #- run: port version
      #- run: sudo port -v install openssl
      #- run: echo "new openssl version"
      #- run: openssl version -a
      #- run: openssl version -d
